# Generated by Django 4.1 on 2022-11-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_topic', models.CharField(blank=True, max_length=30, null=True)),
                ('db_positive_standpoint', models.CharField(max_length=50)),
                ('db_negative_standpoint', models.CharField(max_length=50)),
                ('db_positive_team', models.CharField(blank=True, max_length=30, null=True)),
                ('db_negative_team', models.CharField(blank=True, max_length=30, null=True)),
                ('db_winner', models.CharField(blank=True, max_length=4, null=True)),
                ('db_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debate',
            },
        ),
        migrations.CreateModel(
            name='DebateCompetition',
            fields=[
                ('dbc_id', models.AutoField(primary_key=True, serialize=False)),
                ('dbc_name', models.CharField(max_length=50, unique=True)),
                ('dbc_organizer', models.CharField(blank=True, max_length=50, null=True)),
                ('dbc_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('dbc_first_date', models.DateField(blank=True, null=True)),
                ('dbc_last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debate_competition',
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('fig_id', models.AutoField(primary_key=True, serialize=False)),
                ('fig_ch_name', models.CharField(max_length=50)),
                ('fig_en_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fig_gender', models.CharField(max_length=10)),
                ('fig_birthday', models.DateField(blank=True, null=True)),
                ('fig_deathday', models.DateField(blank=True, null=True)),
                ('fig_day_correction', models.IntegerField()),
                ('fig_detail', models.CharField(max_length=255)),
                ('fig_nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('fig_province', models.CharField(blank=True, max_length=30, null=True)),
                ('fig_city', models.CharField(blank=True, max_length=30, null=True)),
                ('fig_county', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'figure',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('lit_id', models.AutoField(primary_key=True, serialize=False)),
                ('lit_ch_title', models.CharField(max_length=50)),
                ('lit_en_title', models.CharField(blank=True, max_length=100, null=True)),
                ('lit_category', models.CharField(max_length=30)),
                ('lit_published_date', models.DateField(blank=True, null=True)),
                ('lit_detail', models.CharField(max_length=255)),
                ('lit_read_times', models.IntegerField()),
                ('lit_img_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.figure')),
            ],
            options={
                'db_table': 'literature',
            },
        ),
        migrations.CreateModel(
            name='DebateFigure',
            fields=[
                ('db_fig_id', models.AutoField(primary_key=True, serialize=False)),
                ('fig_position', models.CharField(blank=True, max_length=10, null=True)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.debate')),
                ('fig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.figure')),
            ],
            options={
                'db_table': 'debate_figure',
            },
        ),
        migrations.AddField(
            model_name='debate',
            name='dbc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.debatecompetition'),
        ),
        migrations.AddField(
            model_name='debate',
            name='fig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.figure'),
        ),
        migrations.CreateModel(
            name='FigureCategory',
            fields=[
                ('fig_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category')),
                ('fig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.figure')),
            ],
            options={
                'db_table': 'figure_category',
                'unique_together': {('cate', 'fig')},
            },
        ),
    ]
